name: Release
# Workflow will only be triggered by creating tags or branches
on:
  create

jobs:
  style-check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2      
    - name: golangci-lint
      if: github.event_name == 'pull_request'
      uses: golangci/golangci-lint-action@v2
      with:
        # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
        version: v1.29
    - name: install clang-format
      run: sudo apt update && sudo apt install -y clang-format
    - name: Code check
      run: make lint-c
  compile-ebpf-test:
    runs-on: ubuntu-20.04
    needs: [style-check]
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make compile
  go-unit-test:
    runs-on: ubuntu-20.04
    needs: [style-check]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Test
      run: go test -v ./...
  docker-build:
    runs-on: ubuntu-latest
    needs: [compile-ebpf-test, go-unit-test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract Tags name
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        id: tag_env
        shell: bash
        run: |
          echo "##[set-output name=version;]$(echo ${GITHUB_REF##*/})"
      - name: Set up QEMU
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: merbridge/merbridge:${{ steps.tag_env.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
